#!/usr/bin/env python3
from pathlib import Path

import pandas as pd
from tensorboard.backend.event_processing import event_accumulator

if __name__ == "__main__":
    logs_dir = Path("..") / "tensorboard-logs" / "logs" / "imitation"

    for log_dir in logs_dir.glob("2021-05-10*"):
        name = log_dir.name
        print(f"Processing {name}")
        ea = event_accumulator.EventAccumulator(
            str(log_dir),
            purge_orphaned_data=False,
            size_guidance={
                # event_accumulator.COMPRESSED_HISTOGRAMS: 1,
                # event_accumulator.IMAGES: 1,
                # event_accumulator.AUDIO: 1,
                event_accumulator.SCALARS: 0,
                # event_accumulator.HISTOGRAMS: 1,
            },
        )

        ea.Reload()
        print(ea.Tags())
        try:
            pd.DataFrame(ea.Scalars("loss-mean")).to_csv(f"{name}-loss-mean.csv")
            pd.DataFrame(ea.Scalars("expected-value-error-mean")).to_csv(
                f"{name}-expected-value-error-mean.csv"
            )
        except Exception as e:
            print(e)
